# app/services/referral_import_service.py
"""One-click patient registration from an accepted inter-facility referral.

The receiving hospital pulls the patient's shared referral package (live export
from the referring hospital), and — with a single authorised action — creates a
local patient record, its baseline medical profile, and a provenance-tagged copy
of the two most recent visits, all within one atomic transaction.

Design principles:
  * The patient's **Global Patient ID is preserved** verbatim; it is never
    regenerated by the receiving facility.
  * A **new Hospital Membership Number** is minted from the receiving hospital's
    configurable numbering scheme.
  * **Hospital-specific operational data** (membership cards, local hospital
    numbers, billing/financial rows, workflow ids) is intentionally excluded.
  * Recent clinical history is stored in ``ImportedClinicalRecord`` — clearly
    tagged with the originating hospital — rather than reconstructed into native
    operational tables, so cross-tenant staff/service/catalogue ids never dangle
    and local queues/billing stay clean.
  * Everything is audited in ``ReferralImportLog`` with full provenance.
"""
from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any, Optional

from sqlalchemy.orm import Session

from app.core.exceptions import BadRequestError, NotFoundError
from app.models.all_models import (
    ImportedClinicalRecord,
    Patient,
    PatientBaselineProfile,
    PatientBaselineProfileRevision,
    ReferralImportLog,
)
from app.repositories.patient_repository import PatientRepository
from app.services.referral_service import ReferralService
from app.services.hospital_number_service import HospitalNumberService
from app.utils.security_event_util import record_security_event

# Baseline profile columns we accept from the imported package.
_BASELINE_FIELDS = (
    "rhesus_factor", "g6pd_status", "hepatitis_b_status", "hepatitis_c_status",
    "hiv_status", "blood_sugar_baseline", "lipid_profile_baseline",
    "known_allergies", "chronic_conditions", "existing_diagnoses",
    "long_term_medications", "past_medical_history", "past_surgical_history",
    "family_history", "social_history", "immunization_history",
    "obstetric_history", "disability_info", "organ_donor",
    "baseline_height_cm", "baseline_weight_kg", "additional_notes",
)

# Demographic / contact fields imported onto the local Patient record. Explicitly
# excludes hospital_number, membership cards, billing and workflow identifiers.
_DEMOGRAPHIC_FIELDS = (
    "first_name", "last_name", "middle_name", "marital_status",
    "phone_number", "alternate_phone_number", "email", "address", "city",
    "state", "country", "allergies", "chronic_conditions",
    "emergency_contact_name", "emergency_contact_phone",
    "emergency_contact_relationship", "next_of_kin_name", "next_of_kin_phone",
    "next_of_kin_relationship", "next_of_kin_address", "national_identifier",
    "national_identifier_type",
)

# Clinical sections attached to a visit that we import as provenance records.
_VISIT_CLINICAL_SECTIONS = (
    "Consultation", "Diagnosis", "TriageAssessment", "VitalSigns",
    "VitalsRecord", "ClinicalNote", "Prescription", "PrescriptionItem",
    "LabOrder", "LabResult", "RadiologyOrder", "ProcedureOrder",
)

_VISIT_DATE_KEYS = ("check_in_time", "visit_date", "start_time", "date_created",
                    "created_at")


def _parse_dt(v: Any) -> Optional[datetime]:
    if isinstance(v, datetime):
        return v
    if isinstance(v, str) and v:
        for fmt in ("%Y-%m-%dT%H:%M:%S.%f", "%Y-%m-%dT%H:%M:%S",
                    "%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
            try:
                return datetime.strptime(v[:26], fmt)
            except ValueError:
                continue
    return None


def _parse_date(v: Any) -> Optional[date]:
    if isinstance(v, date) and not isinstance(v, datetime):
        return v
    dt = _parse_dt(v)
    return dt.date() if dt else None


def _coerce_enum(enum_cls, value):
    """Map a serialized enum value/name back to the enum member; None if it
    cannot be resolved (demographics still import; clinician can amend)."""
    if value is None or enum_cls is None:
        return None
    for member in enum_cls:
        if value in (member.value, member.name) or str(value) == str(member.value):
            return member
    return None


class ReferralImportService:
    def __init__(self, db: Session) -> None:
        self.db = db
        self.repo = PatientRepository(db)

    # ------------------------------------------------------------------
    # Package retrieval + analysis
    # ------------------------------------------------------------------
    def _fetch_package(self, referral_id: int, *, requesting_tenant_id: int,
                       actor_user_id: Optional[int]) -> dict:
        record = ReferralService(self.db).get_referral_record(
            referral_id, requesting_tenant_id=requesting_tenant_id,
            actor_user_id=actor_user_id,
        )
        payload = record.get("payload") or {}
        if not payload.get("patient"):
            raise NotFoundError(
                message="The referral package does not contain patient details."
            )
        return record

    def _find_local_by_global_id(self, global_id: str) -> Optional[Patient]:
        if not global_id:
            return None
        return (
            self.db.query(Patient)
            .filter(Patient.global_patient_id == global_id,
                    Patient.is_deleted.is_(False))
            .first()
        )

    def _recent_visits(self, payload: dict, limit: int = 2) -> list[dict]:
        sections = payload.get("sections") or {}
        visits = list(sections.get("Visit") or [])

        def _key(v: dict):
            for k in _VISIT_DATE_KEYS:
                dt = _parse_dt(v.get(k))
                if dt:
                    return dt
            return datetime.min

        visits.sort(key=_key, reverse=True)
        return visits[:limit]

    def preview(self, referral_id: int, *, requesting_tenant_id: int,
                actor_user_id: Optional[int] = None) -> dict:
        """Non-mutating analysis powering the receiving-facility review screen:
        the package, an import plan (what will be created), duplicate matches,
        and validation warnings."""
        record = self._fetch_package(
            referral_id, requesting_tenant_id=requesting_tenant_id,
            actor_user_id=actor_user_id)
        payload = record["payload"]
        patient = payload.get("patient") or {}
        global_id = payload.get("global_patient_id")

        existing = self._find_local_by_global_id(global_id)
        dupes = []
        try:
            candidates = self.repo.find_possible_duplicates(
                first_name=patient.get("first_name"),
                last_name=patient.get("last_name"),
                middle_name=patient.get("middle_name"),
                phone_number=patient.get("phone_number"),
                date_of_birth=_parse_date(patient.get("date_of_birth")),
                national_identifier=patient.get("national_identifier"),
                previous_record_identifiers=[],
            ) or []
            dupes = [{"id": c.id, "hospital_number": c.hospital_number,
                      "name": f"{c.first_name or ''} {c.last_name or ''}".strip()}
                     for c in candidates]
        except Exception:
            dupes = []

        warnings = []
        if not patient.get("first_name") or not patient.get("last_name"):
            warnings.append("Patient name is incomplete in the referral package.")
        if not _parse_date(patient.get("date_of_birth")):
            warnings.append("Date of birth is missing or unrecognised.")
        if existing is not None:
            warnings.append(
                f"A local record already exists for this Global Patient ID "
                f"(Hospital No {existing.hospital_number}).")

        recent_visits = self._recent_visits(payload)
        counts = payload.get("counts") or {}
        plan = {
            "will_create_patient": existing is None,
            "will_create_baseline_profile": bool(payload.get("baseline_profile"))
            or bool(patient.get("blood_group") or patient.get("genotype")
                    or patient.get("allergies")),
            "recent_visits_to_import": len(recent_visits),
            "clinical_records_available": {
                k: counts.get(k, 0) for k in _VISIT_CLINICAL_SECTIONS
                if counts.get(k)
            },
            "next_hospital_number": HospitalNumberService(self.db).preview(),
            "global_patient_id_preserved": global_id,
        }
        return {
            "referral_id": record.get("id"),
            "referral_no": record.get("referral_no"),
            "already_imported": existing is not None,
            "existing_patient_id": getattr(existing, "id", None),
            "package": payload,
            "plan": plan,
            "possible_duplicates": dupes,
            "warnings": warnings,
        }

    # ------------------------------------------------------------------
    # Import (atomic, consuming)
    # ------------------------------------------------------------------
    def create_patient_from_referral(
        self, referral_id: int, *, requesting_tenant_id: int,
        actor_user_id: Optional[int] = None,
        overrides: Optional[dict] = None, force: bool = False,
    ) -> dict:
        overrides = overrides or {}
        record = self._fetch_package(
            referral_id, requesting_tenant_id=requesting_tenant_id,
            actor_user_id=actor_user_id)
        payload = record["payload"]
        src_patient = payload.get("patient") or {}
        global_id = payload.get("global_patient_id")
        referral_no = record.get("referral_no")

        if not global_id:
            raise BadRequestError(
                message="The referral package has no Global Patient ID; cannot import."
            )

        existing = self._find_local_by_global_id(global_id)
        if existing is not None:
            raise BadRequestError(
                message="This patient has already been registered here from the "
                        "referral.",
                detail={"existing_patient_id": existing.id,
                        "hospital_number": existing.hospital_number},
            )

        # Duplicate guard (name/DOB/phone) unless the registrar overrides.
        if not force:
            try:
                candidates = self.repo.find_possible_duplicates(
                    first_name=src_patient.get("first_name"),
                    last_name=src_patient.get("last_name"),
                    middle_name=src_patient.get("middle_name"),
                    phone_number=src_patient.get("phone_number"),
                    date_of_birth=_parse_date(src_patient.get("date_of_birth")),
                    national_identifier=src_patient.get("national_identifier"),
                    previous_record_identifiers=[],
                ) or []
            except Exception:
                candidates = []
            if candidates:
                raise BadRequestError(
                    message="Possible duplicate patient record(s) found. Registrar "
                            "review is required before importing.",
                    detail={"possible_duplicate_found": True,
                            "candidate_patient_ids": [c.id for c in candidates]},
                )

        from app.core.enums import Gender, BloodGroup, Genotype

        try:
            # --- Build demographic payload (source values + registrar overrides) ---
            fields: dict[str, Any] = {}
            for f in _DEMOGRAPHIC_FIELDS:
                if f in overrides:
                    fields[f] = overrides[f]
                elif src_patient.get(f) is not None:
                    fields[f] = src_patient.get(f)

            dob = _parse_date(overrides.get("date_of_birth",
                                            src_patient.get("date_of_birth")))
            gender = _coerce_enum(Gender, overrides.get("gender",
                                                        src_patient.get("gender")))
            blood_group = _coerce_enum(BloodGroup, overrides.get(
                "blood_group", src_patient.get("blood_group")))
            genotype = _coerce_enum(Genotype, overrides.get(
                "genotype", src_patient.get("genotype")))

            hospital_number = HospitalNumberService(self.db).allocate_next(
                uniqueness_check=self.repo.hospital_number_exists)

            imported_at = datetime.now(timezone.utc)
            source_tenant_id = record.get("source_tenant_id")
            provenance = {
                "source": "REFERRAL_IMPORT",
                "referral_no": referral_no,
                "referral_id": referral_id,
                "imported_at": imported_at.isoformat(),
                "imported_by_user_id": actor_user_id,
                "global_patient_id": global_id,
            }

            patient = self.repo.create_patient(
                global_patient_id=global_id,          # PRESERVED, never regenerated
                hospital_number=hospital_number,       # freshly minted, local
                first_name=fields.get("first_name") or "Unknown",
                last_name=fields.get("last_name") or "Unknown",
                middle_name=fields.get("middle_name"),
                date_of_birth=dob,
                gender=gender,
                marital_status=fields.get("marital_status"),
                phone_number=fields.get("phone_number"),
                alternate_phone_number=fields.get("alternate_phone_number"),
                email=fields.get("email"),
                address=fields.get("address"),
                city=fields.get("city"),
                state=fields.get("state"),
                country=fields.get("country"),
                blood_group=blood_group,
                genotype=genotype,
                allergies=fields.get("allergies"),
                emergency_contact_name=fields.get("emergency_contact_name"),
                emergency_contact_phone=fields.get("emergency_contact_phone"),
                emergency_contact_relationship=fields.get("emergency_contact_relationship"),
                next_of_kin_name=fields.get("next_of_kin_name"),
                next_of_kin_phone=fields.get("next_of_kin_phone"),
                next_of_kin_relationship=fields.get("next_of_kin_relationship"),
                next_of_kin_address=fields.get("next_of_kin_address"),
                national_identifier=fields.get("national_identifier"),
                national_identifier_type=fields.get("national_identifier_type"),
                identification_details={"referral_provenance": provenance},
                chronic_conditions=fields.get("chronic_conditions"),
            )

            try:
                self.repo.create_registration_event(
                    patient_id=patient.id, registered_by_id=actor_user_id,
                    notes=f"Imported from inter-facility referral {referral_no}.",
                )
            except Exception:
                pass

            counts = {"patient": 1, "baseline_profile": 0,
                      "imported_clinical_records": 0, "visits_imported": 0}

            # --- Baseline Medical Profile ---
            baseline_src = payload.get("baseline_profile") or {}
            profile = PatientBaselineProfile(patient_id=patient.id, version=1)
            has_baseline = False
            for f in _BASELINE_FIELDS:
                val = baseline_src.get(f)
                if f == "known_allergies" and val is None:
                    val = src_patient.get("allergies")
                if f == "chronic_conditions" and val is None:
                    val = src_patient.get("chronic_conditions")
                if val is not None:
                    setattr(profile, f, val)
                    has_baseline = True
            if has_baseline or blood_group or genotype:
                self.db.add(profile)
                self.db.flush()
                self.db.add(PatientBaselineProfileRevision(
                    profile_id=profile.id, patient_id=patient.id, version=1,
                    snapshot_json={"source": "REFERRAL_IMPORT",
                                   "referral_no": referral_no,
                                   "imported_baseline": baseline_src or None},
                    changed_fields=["imported_from_referral"],
                    changed_by_user_id=actor_user_id, changed_at=imported_at,
                ))
                counts["baseline_profile"] = 1

            # --- Recent clinical history (up to 2 most recent visits) ---
            source_hospital = record.get("source_hospital_name")
            sections = payload.get("sections") or {}
            recent = self._recent_visits(payload)
            visit_ids = {v.get("id") for v in recent if v.get("id") is not None}
            for idx, v in enumerate(recent, start=1):
                vdate = None
                for k in _VISIT_DATE_KEYS:
                    vdate = _parse_dt(v.get(k))
                    if vdate:
                        break
                vref = str(v.get("visit_number") or v.get("id") or "")
                self.db.add(ImportedClinicalRecord(
                    patient_id=patient.id, source_tenant_id=source_tenant_id,
                    source_hospital_name=source_hospital,
                    source_referral_no=referral_no, visit_index=idx,
                    visit_reference=vref, visit_date=vdate,
                    record_type="Visit", record_json=v,
                    imported_by_user_id=actor_user_id, imported_at=imported_at,
                ))
                counts["imported_clinical_records"] += 1
                for sec in _VISIT_CLINICAL_SECTIONS:
                    for row in (sections.get(sec) or []):
                        if row.get("visit_id") in visit_ids and (
                                row.get("visit_id") == v.get("id")):
                            self.db.add(ImportedClinicalRecord(
                                patient_id=patient.id,
                                source_tenant_id=source_tenant_id,
                                source_hospital_name=source_hospital,
                                source_referral_no=referral_no, visit_index=idx,
                                visit_reference=vref, visit_date=vdate,
                                record_type=sec, record_json=row,
                                imported_by_user_id=actor_user_id,
                                imported_at=imported_at,
                            ))
                            counts["imported_clinical_records"] += 1
                counts["visits_imported"] += 1

            # --- Audit ledger ---
            modifications = {k: v for k, v in overrides.items()
                             if v is not None} or None
            self.db.add(ReferralImportLog(
                referral_id=referral_id, referral_no=referral_no,
                source_tenant_id=source_tenant_id,
                source_hospital_name=source_hospital,
                target_tenant_id=requesting_tenant_id,
                patient_global_id=global_id, created_patient_id=patient.id,
                hospital_number=hospital_number,
                imported_by_user_id=actor_user_id, imported_at=imported_at,
                records_created=counts, modifications=modifications,
                provenance=provenance,
            ))

            record_security_event(
                self.db, user_id=actor_user_id,
                event_type="REFERRAL_PATIENT_IMPORTED", severity="INFO",
                event_detail=f"Patient imported from referral {referral_no}: "
                             f"hospital no {hospital_number}, global id {global_id}.",
                event_metadata={"referral_id": referral_id,
                                "patient_id": patient.id,
                                "hospital_number": hospital_number,
                                "records_created": counts},
            )

            self.db.commit()
            self.db.refresh(patient)
        except BadRequestError:
            self.db.rollback()
            raise
        except Exception as exc:
            self.db.rollback()
            raise BadRequestError(
                message=f"The referral import could not be completed: {exc}"
            )

        return {
            "patient_id": patient.id,
            "hospital_number": hospital_number,
            "global_patient_id": global_id,
            "referral_no": referral_no,
            "records_created": counts,
            "full_name": f"{patient.first_name or ''} {patient.last_name or ''}".strip(),
        }
